### ISSUE TITLE
How to login to multiple domains?

### ISSUE THREAD

**Issue by chudinanton** [stnoonan/spnego-http-auth-nginx-module#88]
Hello,
We have to log in to multiple domains at the same time.
In the key, we generated several domains.
Separately, they are authorized if we specify "auth_gss_realm"
Tell me please, how to make it so that you can log in to multiple domains?

**Comment by Valeriia-arh** [comment]
I have the same issue. May be you can help?

**Comment by hawicz** [comment]
You should set auth_gss_format_full, and ensure you're using the full principal in whatever you're doing for your authorization checks.
If you're still having trouble, you're going to need to provide a lot more detail, as based on what you've said so far I doubt anyone can really help you much because it's unclear as to what actual problem you're running in to.

**Comment by adtrsa** [comment]
I have the same problem/issue now.
Basically, have nginx running on an Ubuntu VM joined to Active Directory domain A via "net ads join"  using the appropriate krb5.conf and smb.conf etc.

Proxy config looks something like this (real domain name changed):
 auth_gss on;
 auth_gss_keytab /etc/krb5.keytab;
 auth_gss_allow_basic_fallback off;
 auth_gss_realm DOMAIN.A;
 auth_gss_service_name HTTP/myhost.domain.a;

This works fine for DOMAIN.A authenticated users accessing the proxy.
Proper Authorization: Negotiate header with kerberos ticket etc. comes through and verified OK.

Kerberos config looks something like this:
[libdefaults]
default_realm = DOMAIN.A
dns_lookup_realm = false
dns_lookup_kdc = true

However, on the same corporate network exists another Active Directory domain, let's call it DOMAIN.B.
A user on the corprorate network could have a login for both DOMAIN.A and DOMAIN.B.
However, when a user attempts to authenticate via their DOMAIN.B Active Directory login, 
the Authorization: Negotiate header token appears to be NTLM version and not Kerberos.

I suggested adding myhost.domain.a to Trusted Sites etc. in browser, but still only the NTLM token comes through.  I have a suspicion that nothing I change on the myhost.domain.a proxy or Kerberos configuration will change the fact that the user's browser is sending through NTLM token instead of Kerberos token, correct? 

Suppose I get the user's browser to actually send through the DOMAIN.B login Kerberos ticket/token in the request, would I need to/could I add an auth_gss_realm DOMAIN.B entry to the existing auth_gss_realm DOMAIN.A entry and it would just work? Or would I need to obtain an HTTP service principal for/on DOMAIN.B as well (don't think this will work if my host is not part of DOMAIN.B as well).

This is the firs time I had to interface with Active Directory, so please excuse any dumb questions on my part.

**Comment by hawicz** [comment]
Forget about auth_gss_realm for now.  In fact, forget about nginx entirely, because long before you get to the point of the web server doing anything with the request you need to at least configure a trust between the two domains.
That does two things:
* Specifies where the domain controllers (DC) for the "other" domain are
* Provides keys so a client in DOMAIN.B can talk to things in DOMAIN.A

The flow that a browser in DOMAIN.B goes through is a bit like this:
* Using the user's krbtgt/B@B, asks its DC for a service ticket for myhost.domain.a
* DC checks its config, and knows that myhost.domain.a is in DOMAIN.A, so it:
** Returns a referral saying "hey, go talk to the DC over at dc.domain.a (or whatever it actually is)"
** Returns a cross-realm tgt "krbtgt/A@B" so the client can authenticate to the DOMAIN.A DC.
* The browser (or more specifically, the kerberos libraries it's linked against) now asks the DOMAIN.A DC, using the krbtgt/A@B ticket, for a service ticket for myhost.domain.a
* The DOMAIN.A DC checks its config, and knows that myhost.domain.a is in its own domain, and issues a service ticket back to the client.
* Now, finally, the browser can generate the token to authenticate to nginx, and the nginx configuration matters.  I recommend not specifying auth_gss_realm at all, and having your authorization checks use the full principal (i.e. "userfoo@A" or "userbar@B", depending on where the users originated from).
btw, you can also skip auth_gss_service_name, and it should just use whatever happens to be in the keytab.

Note that if you manage to get everything except the last step working, you'll be able to run klist and see the HTTP/myhost.domain.a service ticket in the cred cache.  If you don't see that service ticket, nothing you configure in nginx will make any difference.

**Comment by adtrsa** [comment]
@hawicz Thanks for the detailed explanation, much appreciated! I only learnt about cross-domain trusts yesterday, but the fact that the domain B user browser request had NTLM token was a hint that something is off with the Active Directory domain config. Thanks for explaining what that something is ;) I am setting up a test env locally (2 AD domain DCs etc.) so I can replicate and fix the issue as per your feedback first before interacting with the admins of domain A and B again.

**Comment by stnoonan** [comment]
Keep in mind that the domain options are pretty optional and we try to do the right thing based on the client and the keytab. So you may be overspecifying.
